server: 
  port: 3001
  
eureka:
  client: 
    service-url: 
      defaultZone: http://localhost:4001/eureka/,http://localhost:4003/eureka/,http://localhost:4003/eureka/
spring: 
  application: 
    name: config-server
  cloud: 
    config: 
      label: master
      server: 
        git:
          uri: git@github.com:syuf/config.git
          search-paths: /**
          username: 356418670@qq.com
          password: ah727816
          force-pull: true
  rabbitmq:
    host: 192.168.135.131
    port: 5672
    username: syuf
    password: 123456
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
